services:
  raven:
    image: ravendb/ravendb:5.4-ubuntu-latest
    ports:
      - 8080:8080
    environment:
      - RAVEN_Setup_Mode=None
      - RAVEN_Security_UnsecuredAccessAllowed=PrivateNetwork
      - RAVEN_ARGS=-l
